apiVersion: v1
kind: Service
metadata:
  name: aria2-backend
  labels:
    app: {{ include "webui-aria2.name" . }}
    chart: {{ include "webui-aria2.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.server.port }}
      targetPort: server
      protocol: TCP
      name: server
  selector:
    app: {{ include "webui-aria2.name" . }}
    release: {{ .Release.Name }}