apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "webui-aria2.fullname" . }}
  labels:
    app: {{ include "webui-aria2.name" . }}
    chart: {{ include "webui-aria2.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "webui-aria2.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "webui-aria2.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: server
              containerPort: 6800
              protocol: TCP
            - name: web
              containerPort: 8080
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: :8080/
#              port: http
#          readinessProbe:
#            httpGet:
#              path: :8080/
#              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
