apiVersion: v1
kind: Service
metadata:
  name: {{ include "webui-aria2.fullname" . }}
  labels:
    app: {{ include "webui-aria2.name" . }}
    chart: {{ include "webui-aria2.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.server.port }}
      targetPort: server
      protocol: TCP
      name: server
    - port: {{ .Values.service.web.port }}
      targetPort: web
      protocol: TCP
      name: web
    - port: {{ .Values.service.download.port }}
      targetPort: download
      protocol: TCP
      name: download
  selector:
    app: {{ include "webui-aria2.name" . }}
    release: {{ .Release.Name }}